### ISSUE TITLE
Implement integration with `libpng-ruby`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pngcheck-ruby#5]
After #4 we need to integrate with checking file in memory after loading the file. (in #4 the file load happens within pngcheck)

We can integrate with [libpng-ruby](https://github.com/kwgt/libpng-ruby) like this:

```ruby
require 'png'
dec = PNG::Decoder.new(:color_type => :BGR)
raw = dec << IO.binread("test.png") 
PngCheck.check(raw)
```

**Comment by maxirmx** [comment]
@ronaldtse 
I am not sure I understand this requirement.  PNG is coding standard. The errors that pngcheck finds are coding errors. If we run png file through decoder there is nothing to check.  Decoder will either fail ot create 'flat' (raw) image that is not png-encoded

**Comment by ronaldtse** [comment]
I guess what I was trying to ask for is a way to use pngcheck without considering the file system (with the PNG file loaded into memory). I can see how it doesn’t work as per the example. 

Given an invalid PNG, a PNG library will either:
1. fail to load the image gracefully
2. crash
3. Interpret the image in an erroneous way

The reason why we need pngcheck is in Metanorma — there have been users who generate the document, and in some outputs the PNG works but not in others (eg images in Word and HTML/browsers, or different platforms, use different PNG libraries). The users blame our software for these problems and we don’t want that to happen. The solution is when Metanorma gets these image files, it must err out of these images so the authors (whoever is using Metanorma) needs to fix them. 

As long as we have a cross-platform way to ensure these PNG images work is sufficient. I just don’t want Metanorma to deal with file system path normalization etc so much.

**Comment by maxirmx** [comment]
Then it looks like you are asking for the following:

```ruby
require 'png'
encoded = IO.binread("test.png") 
begin
   PngCheck.check(encoded)
   dec = PNG::Decoder.new(:color_type => :BGR)
   raw = dec << encoded
 rescue PngCheck::CorruptPngError
 # say something
 end
```
